- name: Codecov
  uses: codecov/codecov-action@v3.0.0

arch: amd64

language: java

jdk: 
  - oraclejdk15

cache:
  directories:
  - $HOME/.m2

script:
  - java --version
  - ./mvnw clean install
  - ./mvnw test
